swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: All transactions by account
      description: Return all transactions of an account by current month
      parameters:
        - in: path
          name: accountId
          description: accepts an id from an existing account
          required: true
          type: string
      produces:
        - application/json
      responses: 
        '200':
          description: Return an array of all transactions
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalids path params
        '401':
          description: You must be authenticated
        '403':
          description: Not allowed to get transactions
        '404':
          description: Account id not found
        '500':
          description: Internal server error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: One specific transaction
      description: return one transaction by its id
      parameters:
        - in: path
          name: transactionId
          description: accepts an id from an existing transaction
          required: true
          type: string
      produces:
        - application/json
      responses: 
        '200':
          description: Return an object of a transaction
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalids path params
        '401':
          description: You must be authenticated
        '403':
          description: Not allowed to get transaction
        '404':
          description: Transaction id not found
        '500':
          description: Internal server error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modify a specific transaction
      description: modify a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: accepts an id from an existing transaction
          required: true
          type: string
        - in: body
          name: body
          description: accepts an object with note or category values
          required: true
          schema:
            $ref: '#/definitions/TransactionModification'
      produces:
        - application/json
      responses: 
        '200':
          description: Return an object of a transaction
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalids path params or body values
        '401':
          description: You must be authenticated
        '403':
          description: Not allowed to modify transaction
        '404':
          description: Transaction id not found
        '500':
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionsResponse:
    type: array
    items: 
      type: object
      properties:
        id:
          type: string
        date:
          type: string
        amount:
          type: integer
        description:
          type: string
        balance:
          type: integer
        transaction-type:
          type: string
        note:
          type: string
        category:
          type: string
        userId:
          type: string
        accountId:
          type: string
  TransactionResponse:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      amount:
        type: integer
      description:
        type: string
      balance:
        type: integer
      transaction-type:
        type: string
      note:
        type: string
      category:
        type: string
      userId:
        type: string
      accountId:
        type: string
  TransactionModification:
    type: object
    properties:
      note:
        type: string
      category:
        type: string
          
